ingress:
  enabled: true
  className: nginx
  hosts:
    - host: nora.apatsev.org.ru
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

persistence:
  enabled: true
  size: 10Gi

env:
  NORA_PUBLIC_URL: "https://nora.apatsev.org.ru"

resources:
  limits:
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 128Mi
    cpu: "0.25"
