ingress:
  enabled: true
  className: nginx
  hosts:
    - host: nora-apatsev.duckdns.org
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: nora-tls
      hosts:
        - nora-apatsev.duckdns.org

persistence:
  enabled: true
  size: 10Gi

config:
  server:
    public_url: "https://nora-apatsev.duckdns.org"
  registries:
    enable: "all"
  curation:
    mode: "enforce"
    min_release_age: "7d"
    blocklist_path: "/etc/nora/blocklist.json"
    npm:
      min_release_age: "3d"
    pypi:
      min_release_age: "5d"
  auth:
    enabled: true
    htpasswd:
      existingSecret: nora-htpasswd
      secretKey: users.htpasswd

resources:
  limits:
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 128Mi
    cpu: "0.25"
